version: '3.8'

services:
  neo4j:
    container_name: icap-neo4j
    image: neo4j:5.9.0
    # Use remapped ports to avoid conflicts with existing Neo4j instances
    ports:
      - "7490:7474"  # HTTP - using port 7490 externally
      - "7690:7687"  # Bolt - using port 7690 externally
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_config_strict__validation_enabled=false
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
      - ./docker/neo4j/neo4j.conf:/conf/neo4j.conf
      - ./docker/neo4j/apoc.conf:/conf/apoc.conf
    networks:
      - icap-network
    healthcheck:
      # Check both HTTP and Bolt interfaces
      test: ["CMD", "bash", "-c", 
             "curl -s -I http://localhost:7474 || exit 1; \
              echo 'MATCH (n) RETURN count(n) LIMIT 1' | \
              cypher-shell -u neo4j -p password -a bolt://localhost:7687 || exit 1"]
      interval: 20s
      timeout: 45s
      retries: 15
      start_period: 60s
    restart: unless-stopped

  processing:
    container_name: icap-processing
    build: ./docker/processing
    volumes:
      - ./python_components:/app/python_components
      - ./data:/app/data
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-cyberpunk-gm-screen}
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    networks:
      - icap-network
    depends_on:
      neo4j:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; import os; sys.exit(0 if os.path.exists('/app/health') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  icap-network:
    driver: bridge
    # Enable IPv6 support
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
        - subnet: 2001:db8:1::/64

volumes:
  neo4j_data:
    name: icap_neo4j_data
  neo4j_logs:
    name: icap_neo4j_logs
  neo4j_import:
    name: icap_neo4j_import
  neo4j_plugins:
    name: icap_neo4j_plugins