version: '3.8'

services:
  neo4j:
    container_name: icap-neo4j
    image: neo4j:5.5.0
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
    networks:
      - icap-network

  processing:
    container_name: icap-processing
    build: ./docker/processing
    volumes:
      - ./python_components:/app/python_components
      - ./data:/app/data
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    networks:
      - icap-network
    depends_on:
      - neo4j

networks:
  icap-network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: