name: Build Docker Images

on:
  push:
    branches: [ main, staging ]
    paths:
      - 'docker/**'
      - 'python_components/**'
  pull_request:
    branches: [ main, staging ]
    paths:
      - 'docker/**'
      - 'python_components/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build processing container
        uses: docker/build-push-action@v4
        with:
          context: ./docker/processing
          push: false
          load: true
          tags: icap-processing:latest
      - name: Build neo4j container
        uses: docker/build-push-action@v4
        with:
          context: ./docker/neo4j
          push: false
          load: true
          tags: icap-neo4j:latest