name: Dependency Scanning

on:
  schedule:
    - cron: '0 0 * * 0'  # Run once a week on Sunday
  workflow_dispatch:  # Allow manual triggering

jobs:
  scan-python-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety
      - name: Run safety check
        run: |
          safety check -r docker/processing/requirements.txt --full-report

  scan-node-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Run npm audit
        run: |
          cd cloud-functions
          for function_dir in */; do
            if [ -f "$function_dir/package.json" ]; then
              cd "$function_dir"
              npm audit
              cd ..
            fi
          done

  scan-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build processing container
        uses: docker/build-push-action@v4
        with:
          context: ./docker/processing
          push: false
          load: true
          tags: icap-processing:latest
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'icap-processing:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'