name: Run Tests

on:
  workflow_run:
    workflows: ["Build Cloud Functions", "Build Docker Images"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      
      # Test Cloud Functions
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install cloud function dependencies
        run: |
          cd cloud-functions
          for function_dir in */; do
            if [ -f "$function_dir/package.json" ]; then
              cd "$function_dir"
              npm install
              cd ..
            fi
          done
      - name: Run cloud function tests
        run: |
          cd cloud-functions
          for function_dir in */; do
            if [ -f "$function_dir/package.json" ] && grep -q "\"test\":" "$function_dir/package.json"; then
              cd "$function_dir"
              npm test
              cd ..
            fi
          done
      
      # Test Python components
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: pip install -r docker/processing/requirements.txt
      - name: Install Python test dependencies
        run: pip install pytest pytest-cov
      - name: Run Python tests
        run: pytest python_components/
      
      # Security scanning
      - name: Build processing container for scanning
        uses: docker/build-push-action@v4
        with:
          context: ./docker/processing
          push: false
          load: true
          tags: icap-processing:latest
      - name: Run security scans
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'icap-processing:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'